spring:
  profiles:
    active:
    - dev
    
#开发环境
---
spring:
  profites: dev
  application:
    name: springcloud-config-dev

#测试环境
---
spring:
  profiles: test
  application:
    name: springcloud-config-test
    #请保存为UTF-8格式
