spring:
  profiles:
    active:
    - dev

#config开发客户端配置信息
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: springcloud-config-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://114.116.190.45:3306/cloud_db_01              # 数据库名
    username: root
    password: a9530.A.
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.bd.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: springcloud-config-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

# Eureka的info信息 $project.artifactId$ 取的pom.xml中的数据
info:
  app.name: springcloud
  company.name: www.nianshaoyouwei.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#config测试客户端配置信息
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: springcloud-config-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://114.116.190.45:3306/cloud_db_02              # 数据库名
    username: root
    password: a9530.A.
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.bd.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: springcloud-config-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

# Eureka的info信息 $project.artifactId$ 取的pom.xml中的数据
info:
  app.name: springcloud
  company.name: www.nianshaoyouwei.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$
